import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex gap-x-[30px] bg-[#F5F5F5] ${inter.className}`}>
        <Sidebar />
        <div className="flex-1 mt-2">{children}</div>
      </body>
    </html>
  );
}
